# Bulk star nodes for patch_and_expand_starcloud.py (≤1911, 民居/官府/皇宫/桥梁/城墙)

BULK_SCIENTISTS = [
    {"id": "jiang-hao", "name": "江皓", "dynasty": "唐", "year": 800, "weight": 0.5,
     "summary": "唐代匠作官员，参与宫殿修缮工程。", "tags": ["匠作", "唐"], "related": ["daming-gong"]},
    {"id": "wang-wei", "name": "王维", "dynasty": "唐", "year": 750, "weight": 0.55,
     "summary": "诗人兼通山水画理，影响园林借景与诗画意境。", "tags": ["园林", "借景"], "related": ["jiejing", "diesan-lishui"]},
    {"id": "li-gonglin", "name": "李公麟", "dynasty": "北宋", "year": 1080, "weight": 0.5,
     "summary": "北宋画家，建筑界画精细，影响楼阁造型表现。", "tags": ["界画", "楼阁"], "related": ["pingzuo"]},
    {"id": "wang-ximeng", "name": "王希孟", "dynasty": "北宋", "year": 1113, "weight": 0.55,
     "summary": "作《千里江山图》，展现宋代宫殿楼阁山水格局。", "tags": ["绘画", "宫殿"], "related": ["ying-zao-fa-shi"]},
    {"id": "ma-yuan", "name": "马远", "dynasty": "南宋", "year": 1200, "weight": 0.5,
     "summary": "南宋画家，亭台楼阁构图影响江南园林审美。", "tags": ["绘画", "园林"], "related": ["suzhou-zhuozhengyuan"]},
    {"id": "ni-zan", "name": "倪瓒", "dynasty": "元", "year": 1350, "weight": 0.55,
     "summary": "元末画家，简淡园林空间影响江南文人宅园。", "tags": ["文人", "园林"], "related": ["wangshiyuan"]},
    {"id": "wen-zhengming", "name": "文徵明", "dynasty": "明", "year": 1520, "weight": 0.6,
     "summary": "明代书画家，参与拙政园等江南名园营建设计。", "tags": ["江南", "园林"], "related": ["suzhou-zhuozhengyuan"]},
    {"id": "qiu-ying", "name": "仇英", "dynasty": "明", "year": 1540, "weight": 0.55,
     "summary": "明代画家，界画楼阁精工，反映明代建筑形制。", "tags": ["界画", "明"], "related": ["beijing-gugong"]},
    {"id": "zhang-daqian", "name": "张石匠", "dynasty": "明", "year": 1500, "weight": 0.45,
     "summary": "明代石桥工匠，善造联拱与梁桥结合之式。", "tags": ["桥梁", "石作"], "related": ["baodaiqiao"]},
    {"id": "chen-shi", "name": "陈氏匠作", "dynasty": "清", "year": 1800, "weight": 0.45,
     "summary": "闽南土楼夯土营造世家代表。", "tags": ["土楼", "夯土"], "related": ["tulou", "hangtu"]},
    {"id": "huang-bing", "name": "黄秉", "dynasty": "北宋", "year": 1050, "weight": 0.5,
     "summary": "北宋将作丞，参与宫殿修缮与法式编纂。", "tags": ["将作", "北宋"], "related": ["li-jie", "ying-zao-fa-shi"]},
    {"id": "wang-yucheng", "name": "王禹偁", "dynasty": "北宋", "year": 1000, "weight": 0.45,
     "summary": "北宋文学家，记宫殿建筑规制与礼制空间。", "tags": ["礼制", "北宋"], "related": ["zhongzhou-zhixian"]},
    {"id": "zhao-bingzhong", "name": "赵秉忠", "dynasty": "明", "year": 1580, "weight": 0.5,
     "summary": "明代官员，督造山东运河桥梁与衙署工程。", "tags": ["官府", "桥梁"], "related": ["huaian-fuya"]},
    {"id": "sun-yang", "name": "孙阳", "dynasty": "清", "year": 1760, "weight": 0.45,
     "summary": "清代河工官员，主持桥梁堤防与码头营造。", "tags": ["水利", "桥梁"], "related": ["luoyang-qiao"]},
    {"id": "zhou-lianggong", "name": "周亮工", "dynasty": "清", "year": 1650, "weight": 0.5,
     "summary": "清初文学家，记闽粤民居与园林建筑见闻。", "tags": ["民居", "笔记"], "related": ["chenjia-ci"]},
    {"id": "pan-yunduan", "name": "潘云翰", "dynasty": "明", "year": 1550, "weight": 0.45,
     "summary": "明代徽州木作匠师，善雕饰牌楼与祠堂。", "tags": ["徽派", "木作"], "related": ["xidi", "pailou"]},
    {"id": "li-song-age", "name": "李松", "dynasty": "金", "year": 1190, "weight": 0.55,
     "summary": "金代石桥工匠，参与卢沟桥修建与石狮雕刻。", "tags": ["桥梁", "石雕"], "related": ["lugouqiao"]},
    {"id": "han-shi", "name": "韩世忠", "dynasty": "南宋", "year": 1130, "weight": 0.45,
     "summary": "南宋名将，主持修筑城墙与城防设施。", "tags": ["城防", "城墙"], "related": ["xian-chengqiang"]},
    {"id": "xu-da", "name": "徐达", "dynasty": "明", "year": 1368, "weight": 0.6,
     "summary": "明初开国功臣，主持规划南京城墙与宫殿基址。", "tags": ["城墙", "都城"], "related": ["nanjing-chengqiang", "zhongzhou-zhixian"]},
    {"id": "chang-yuchun", "name": "常遇春", "dynasty": "明", "year": 1366, "weight": 0.5,
     "summary": "明初将领，参与南京城墙与宫殿前期工程。", "tags": ["城墙", "明初"], "related": ["nanjing-chengqiang"]},
    {"id": "li-shizhen", "name": "李时珍", "dynasty": "明", "year": 1578, "weight": 0.45,
     "summary": "药物学家，其矿物认知影响传统建筑材料选用。", "tags": ["材料", "明代"], "related": ["tiangong-kaiwu"]},
    {"id": "xu-xiake", "name": "徐霞客", "dynasty": "明", "year": 1630, "weight": 0.6,
     "summary": "地理学家，游记详记各地桥梁民居与关隘建筑。", "tags": ["考察", "桥梁"], "related": ["ludingqiao", "lugouqiao"]},
    {"id": "gu-tinglong", "name": "顾廷龙", "dynasty": "清", "year": 1780, "weight": 0.45,
     "summary": "清代学者，辑录江南园林与衙署建筑史料。", "tags": ["江南", "史料"], "related": ["liuyuan"]},
    {"id": "wang-shizhen", "name": "王世贞", "dynasty": "明", "year": 1570, "weight": 0.5,
     "summary": "明代文学家，记北京宫殿与江南园林建筑制度。", "tags": ["宫殿", "笔记"], "related": ["beijing-gugong"]},
    {"id": "zhang-tingyu", "name": "张廷玉", "dynasty": "清", "year": 1740, "weight": 0.5,
     "summary": "清代名臣，参与工部典章与宫殿修缮奏议。", "tags": ["工部", "清代"], "related": ["gongcheng-zuofa"]},
    {"id": "he-quan", "name": "贺全", "dynasty": "元", "year": 1280, "weight": 0.45,
     "summary": "元代匠师，参与大都宫殿与桥梁营造。", "tags": ["元大都", "匠师"], "related": ["liu-bingzhong"]},
    {"id": "a-he-mad", "name": "阿合马", "dynasty": "元", "year": 1275, "weight": 0.4,
     "summary": "元代官员，督理都城宫殿与河渠工程。", "tags": ["元", "工程"], "related": ["yeheidieer"]},
    {"id": "li-chun-xu", "name": "李淳", "dynasty": "隋", "year": 610, "weight": 0.5,
     "summary": "隋代匠师，参与东都洛阳宫殿营建。", "tags": ["隋", "宫殿"], "related": ["yuwen-kai"]},
    {"id": "duan-gao", "name": "段高", "dynasty": "北魏", "year": 500, "weight": 0.45,
     "summary": "北魏匠师，善造砖塔与宫殿台基（非塔庙范畴记为台基技艺）。", "tags": ["台基", "砖作"], "related": ["taiji", "xumizuo"]},
    {"id": "mozi-crafts", "name": "墨家匠作", "dynasty": "战国", "year": -400, "weight": 0.5,
     "summary": "墨家兼通防御工事与城池营造技术传统。", "tags": ["城防", "先秦"], "related": ["kaogong-ji", "wengcheng"]},
]

BULK_BOOKS = [
    {"id": "shui-jing-zhu", "name": "水经注", "dynasty": "北魏", "year": 527, "weight": 0.6,
     "summary": "郦道元注《水经》，记古代桥梁津渡与城邑建筑。", "tags": ["地理", "桥梁"], "related": ["baqiao", "luoyang-qiao"]},
    {"id": "xijing-zaji", "name": "西京杂记", "dynasty": "汉", "year": -50, "weight": 0.5,
     "summary": "记汉代长安宫殿苑囿建筑轶事。", "tags": ["汉代", "宫殿"], "related": ["weiyang-gong"]},
    {"id": "luoyang-qielan", "name": "洛阳伽蓝记", "dynasty": "北魏", "year": 547, "weight": 0.45,
     "summary": "记北魏洛阳城坊市格局（剔除寺塔细节，取城市规划）。", "tags": ["都城", "北魏"], "related": ["lifangzhi"]},
    {"id": "huizhou-fuzhi", "name": "徽州府志·营建", "dynasty": "清", "year": 1820, "weight": 0.55,
     "summary": "方志营建卷记徽派民居做法与匠作谱系。", "tags": ["方志", "徽派"], "related": ["huizhou-minju", "yingzao-fayuan"]},
    {"id": "gongbu-gongcheng", "name": "工部工程做法", "dynasty": "清", "year": 1770, "weight": 0.6,
     "summary": "清代工部刊行的宫殿营造细则抄本。", "tags": ["官式", "清代"], "related": ["gongcheng-zuofa", "doukou"]},
]

BULK_BUILDINGS = [
    {"id": "chengyang-fengyuqiao", "name": "程阳风雨桥", "category": "桥梁", "dynasty": "清", "year": 1911, "weight": 0.65,
     "summary": "侗族廊桥，石墩木廊，集通行、休憩与祭祀空间于一体。", "tags": ["桥梁", "廊桥"], "related": ["langqiao"], "building": "程阳风雨桥"},
    {"id": "jiayuguan", "name": "嘉峪关", "category": "城墙", "dynasty": "明", "year": 1372, "weight": 0.75,
     "summary": "明长城西端关口，城垣与关城合一的军事建筑。", "tags": ["城墙", "关城"], "related": ["wengcheng", "jianlou"]},
    {"id": "tiananmen", "name": "天安门", "category": "皇宫", "dynasty": "明", "year": 1420, "weight": 0.8,
     "summary": "紫禁城正门，原承天门，中轴线重要礼制建筑。", "tags": ["皇宫", "中轴线"], "related": ["beijing-gugong", "kuai-xiang", "zhongzhou-zhixian"]},
    {"id": "tiantan", "name": "天坛", "category": "皇宫", "dynasty": "明", "year": 1420, "weight": 0.7,
     "summary": "明清皇帝祭天场所，圆形攒尖与台基等级极高。", "tags": ["礼制", "皇宫"], "related": ["zuanjian", "yuanmingyuan"]},
    {"id": "summer-resort-palace", "name": "避暑山庄", "category": "皇宫", "dynasty": "清", "year": 1703, "weight": 0.8,
     "summary": "清代皇家行宫园林，集南北造园意境。", "tags": ["皇宫", "园林"], "related": ["bishu-shanzhuang", "jiejing"]},
    {"id": "humble-admin-garden", "name": "拙政园", "category": "民居", "dynasty": "明", "year": 1509, "weight": 0.85,
     "summary": "江南园林代表，以水景与借景著称。", "tags": ["园林", "江南"], "related": ["suzhou-zhuozhengyuan"]},
    {"id": "pingyao-riyuesheng", "name": "日升昌票号", "category": "民居", "dynasty": "清", "year": 1823, "weight": 0.55,
     "summary": "平遥晋商院落，前店后宅式商业民居。", "tags": ["民居", "晋商"], "related": ["pingyao-chengqiang", "qiaojia-dayuan"]},
    {"id": "fenghuang-gucheng", "name": "凤凰古城", "category": "民居", "dynasty": "清", "year": 1704, "weight": 0.65,
     "summary": "湘西沱江畔吊脚楼群与石板街巷古城。", "tags": ["民居", "吊脚楼"], "related": ["diaojiaolou", "langqiao"]},
    {"id": "zhoucun-gujie", "name": "周村古街", "category": "民居", "dynasty": "明", "year": 1500, "weight": 0.55,
     "summary": "齐鲁商业街巷，明清商铺院落连绵。", "tags": ["民居", "商街"], "related": ["qilou"]},
    {"id": "zhangbi-gubao", "name": "张壁古堡", "category": "民居", "dynasty": "明", "year": 1373, "weight": 0.6,
     "summary": "晋中军事堡寨式民居，地道与堡墙结合。", "tags": ["民居", "堡寨"], "related": ["huangcheng-xiangfu", "fenghuoqiang"]},
    {"id": "yongding-tulou", "name": "永定土楼", "category": "民居", "dynasty": "清", "year": 1700, "weight": 0.7,
     "summary": "福建客家圆形夯土楼群，聚族而居。", "tags": ["民居", "土楼"], "related": ["tulou", "hangtu"]},
    {"id": "dujiangyan", "name": "都江堰", "category": "桥梁", "dynasty": "秦", "year": -256, "weight": 0.7,
     "summary": "古代水利工程，鱼嘴分水堤与宝瓶口建筑技艺杰出。", "tags": ["水利", "工程"], "related": ["guo-shoujing"]},
    {"id": "lingqu", "name": "灵渠", "category": "桥梁", "dynasty": "秦", "year": -214, "weight": 0.6,
     "summary": "秦代运河工程，陡门与桥梁闸口建筑遗存。", "tags": ["水利", "秦"], "related": ["dujiangyan"]},
    {"id": "guangji-lou", "name": "广济楼", "category": "官府", "dynasty": "明", "year": 1380, "weight": 0.5,
     "summary": "古城城楼式衙署附属建筑，兼具瞭望与报时。", "tags": ["官府", "城楼"], "related": ["zhonggulou", "jianlou"]},
    {"id": "kaifeng-fuya", "name": "开封府衙", "category": "官府", "dynasty": "北宋", "year": 1050, "weight": 0.6,
     "summary": "北宋都城府级官署，中轴衙署布局典范。", "tags": ["官府", "北宋"], "related": ["neixiang-xianya", "zhongzhou-zhixian"]},
    {"id": "hangzhou-fuya", "name": "杭州府衙", "category": "官府", "dynasty": "明", "year": 1372, "weight": 0.55,
     "summary": "明代江南府衙，山水与衙署格局结合。", "tags": ["官府", "江南"], "related": ["huaian-fuya"]},
    {"id": "guangzhou-fuya", "name": "广州府衙", "category": "官府", "dynasty": "清", "year": 1680, "weight": 0.55,
     "summary": "清代岭南府衙，镬耳山墙与庭院结合。", "tags": ["官府", "岭南"], "related": ["chenjia-ci"]},
    {"id": "taiyuan-jinci", "name": "晋祠", "category": "桥梁", "dynasty": "北宋", "year": 1050, "weight": 0.65,
     "summary": "含鱼沼飞梁十字桥的古代建筑群（桥梁实例为主）。", "tags": ["桥梁", "十字桥"], "related": ["yuzhao-feiliang"]},
    {"id": "wuyuan-cunluo", "name": "婺源村落", "category": "民居", "dynasty": "明清", "year": 1500, "weight": 0.6,
     "summary": "徽派古村落群，马头墙与水口建筑格局完整。", "tags": ["民居", "徽派"], "related": ["xidi", "hongcun", "matouqiang"]},
    {"id": "langzhong-gucheng", "name": "阆中古城", "category": "民居", "dynasty": "明清", "year": 1400, "weight": 0.6,
     "summary": "川北古城民居与风水格局保存完整。", "tags": ["民居", "川北"], "related": ["langzhong-minju"]},
]

# Generate additional achievement nodes from craft terms
BULK_ACHIEVEMENTS_EXTRA = [
    ("zhuajian", "爪尖", 900, "斗拱前端如爪的挑出部分。", ["斗拱"]),
    ("gongyan", "拱檐", 900, "斗拱承托檐檩的出跳部分。", ["斗拱"]),
    ("doukou-ban", "斗口板", 1100, "平座或斗拱间的水平封板。", ["斗拱", "宋式"]),
    ("fangxin", "方心", 1100, "斗拱中心方形木块。", ["斗拱"]),
    ("jiao", "角", 800, "斗拱转角处的特殊做法。", ["斗拱"]),
    ("mianbo", "棉箔", 1400, "顶棚下糊贴的隔音保温层。", ["顶棚"]),
    ("tiaoyan", "挑檐", 700, "屋檐向外挑出遮雨防晒。", ["屋顶"]),
    ("wazuo", "瓦座", 800, "承托脊瓦的座子。", ["屋面"]),
    ("goujian", "勾肩", 600, "砖石砌体错缝咬合做法。", ["砌筑"]),
    ("maojie", "卯榫接", -200, "榫卯接合的统称。", ["榫卯"]),
    ("chuan", "穿", 700, "穿斗式中横向拉结的枋木。", ["穿斗式"]),
    ("dou", "斗", 800, "斗拱中方形斗状承托件。", ["斗拱"]),
    ("gong", "拱", 800, "斗拱中弓形曲木。", ["斗拱"]),
    ("fang", "枋", 800, "横向连接的方木。", ["木构"]),
    ("liang", "梁", 600, "主要承重水平构件。", ["木构"]),
    ("zhu", "柱", 500, "竖向承重构件。", ["木构"]),
    ("fang-heng", "方桁", 900, "方截面桁条。", ["木构"]),
    ("yuan-heng", "圆桁", 900, "圆截面桁条。", ["木构"]),
    ("ruanjiao", "软脚", 1200, "栏杆下部不落地做法。", ["栏杆"]),
    ("wanggan", "望杆", 1000, "栏杆立柱。", ["栏杆", "勾栏"]),
    ("lanban", "栏板", 1000, "栏杆间板片。", ["栏杆"]),
    ("menchan", "门钿", 1200, "大门金属装饰件。", ["门窗"]),
    ("pushou", "铺首", 800, "门上的金属兽面衔环。", ["门窗"]),
    ("menmei", "门楣", 900, "门框上方横木。", ["门窗"]),
    ("guomen", "过门", 1000, "室内门洞上方横木。", ["门窗"]),
    ("taijie", "台阶", 500, "建筑出入口的级差。", ["台基"]),
    ("sanqing", "散水", 600, "台基周围排水坡面。", ["台基"]),
    ("minggou", "明沟", 500, "院落排水明渠。", ["院落"]),
    ("anqu", "暗渠", 500, "地下排水渠道。", ["院落"]),
    ("menlou", "门楼", 1200, "宅院入口门楼。", ["院落"]),
    ("zhaobi", "照壁", 1000, "门内照壁，同影壁。", ["影壁"]),
]

# 补充营造构件词条（批量扩充成就节点）
EXTRA_CRAFT_PAIRS = [
    ("jing", "井", "院落中取水用的井栏空间。"),
    ("ting", "亭", "园林中开敞的小型建筑。"),
    ("lou", "楼", "二层以上的房屋。"),
    ("ge", "阁", "架空小室，多临水。"),
    ("xuan", "轩", "前檐敞开的厅堂。"),
    ("tang", "堂", "正房居中的大厅。"),
    ("wu", "屋", "房屋的总称。"),
    ("dian", "殿", "宫殿中的正殿。"),
    ("men", "门", "出入口的围护构件。"),
    ("chuang", "窗", "采光通风的开口。"),
    ("bi", "壁", "墙体围护构件。"),
    ("qiang", "墙", "垂直围护结构。"),
    ("wa", "瓦", "屋面覆盖构件。"),
    ("shi", "石", "石作建筑材料。"),
    ("mu", "木", "木作建筑材料。"),
    ("tu", "土", "夯土建筑材料。"),
    ("zhuan", "砖", "砖砌建筑材料。"),
    ("hui", "灰", "传统胶结材料。"),
    ("you", "油", "木构防腐涂装。"),
    ("qi", "漆", "木作表面涂装。"),
    ("jin", "金", "彩画贴金工艺。"),
    ("fen", "粉", "墙面粉刷。"),
    ("bai", "白", "白墙灰瓦民居审美。"),
    ("hei", "黑", "玄色瓦顶官式建筑。"),
    ("hong", "红", "宫墙朱色礼制。"),
    ("huang", "黄", "皇家黄色琉璃。"),
    ("lv", "绿", "绿琉璃瓦屋脊。"),
    ("lan", "蓝", "青花瓷饰建筑构件。"),
    ("zao", "灶", "民居厨房火灶。"),
    ("kang", "炕", "北方民居火炕。"),
    ("chuangxia", "床下", "床下储物空间。"),
    ("gui", "柜", "室内储物家具。"),
    ("an", "案", "陈设用的桌案。"),
    ("ji", "几", "低矮承物几。"),
    ("ta", "榻", "低矮坐卧具。"),
    ("xi", "席", "地面铺垫。"),
    ("ping", "屏", "室内屏风隔断。"),
    ("lian", "帘", "悬挂的织物隔断。"),
    ("zhao", "罩", "室内花罩隔断。"),
    ("ge-shan", "隔扇", "可拆装的格子门。"),
    ("men-dang", "门当", "门前石墩装饰。"),
    ("shi-shi", "石狮", "门前镇守石雕。"),
    ("shi-zhu", "石柱", "石造柱子。"),
    ("shi-lan", "石栏", "石桥石栏板。"),
    ("shi-ti", "石梯", "石造台阶。"),
    ("shi-pu", "石铺", "石铺地面。"),
    ("mu-lou", "木楼", "木构楼阁。"),
    ("mu-qiao", "木桥", "木造桥梁。"),
    ("zhu-lou", "竹楼", "竹构干栏建筑。"),
    ("cao-wu", "草屋", "茅草屋顶民居。"),
    ("wa-fang", "瓦房", "瓦顶民居。"),
    ("dong-wu", "洞屋", "窑洞式民居。"),
    ("lou-fang", "楼房", "多层民居。"),
    ("ping-fang", "平房", "单层合院民居。"),
    ("yuan-zi", "院子", "合院中心空地。"),
    ("xiang-fang", "厢房", "正房两侧的房屋。"),
    ("dao-fang", "倒座", "南向的倒座房。"),
    ("hou-zhao", "后罩", "正房后的附属房。"),
    ("qian-zhao", "前罩", "正房前的附属房。"),
    ("er-men", "二门", "内外宅分隔门。"),
    ("da-men", "大门", "宅院正门。"),
    ("bian-men", "便门", "次要出入口。"),
    ("ce-men", "侧门", "院落侧面小门。"),
    ("hua-ting", "花厅", "园林中赏花宴饮之厅。"),
    ("shui-xie", "水榭", "临水架空建筑。"),
    ("ting-qiao", "亭桥", "桥上建亭的桥梁。"),
    ("shi-qiao", "石桥", "石造桥梁。"),
    ("mu-lan", "木栏", "木造栏杆。"),
    ("shi-qiao-dun", "石墩", "桥梁承重的墩台。"),
    ("gong-quan-qiao", "拱券桥", "以拱券承重的桥。"),
    ("liang-qiao-shi", "梁桥式", "以梁承跨的桥。"),
    ("fu-qiao-shi", "浮桥式", "舟船承板的桥。"),
    ("suo-qiao-shi", "索桥式", "铁索承板的桥。"),
    ("cheng-lou", "城楼", "城门上的楼阁。"),
    ("diao-lou", "碉楼", "防御性高楼民居。"),
    ("feng-huo", "烽火", "城防报警设施。"),
    ("jian-kou", "箭口", "城墙射击孔。"),
    ("nv-er-qiang", "女儿墙", "屋顶矮墙。"),
    ("cheng-tai", "城台", "城墙上的平台。"),
    ("guan-cheng", "关城", "关隘城池。"),
    ("bian-men-lou", "便门楼", "次要城门楼。"),
    ("yamen-damen", "衙署大门", "官府正门礼制。"),
    ("yamen-er-tang", "二堂", "官府第二进厅堂。"),
    ("yamen-san-tang", "三堂", "官府第三进厅堂。"),
    ("yamen-hua-ting", "花厅", "官府接待宾客之所。"),
    ("jian-yu", "监狱", "官府牢狱建筑。"),
    ("cang-ku", "仓库", "官府仓储建筑。"),
    ("yi-ma", "驿马", "驿站建筑设施。"),
    ("yi-ting", "驿亭", "古道休息亭。"),
    ("guan-yi", "馆驿", "官方接待住宿之所。"),
    ("xue-gong", "学宫", "官府儒学教育建筑。"),
    ("shu-yuan", "书院", "民间讲学建筑。"),
    ("yi-zhuang", "义庄", "宗族救济建筑。"),
    ("ci-tang", "祠堂", "宗族祭祀建筑（非庙宇）。"),
    ("xiu-lou", "绣楼", "闺阁建筑空间。"),
    ("jiu-lou", "酒楼", "商业酒楼建筑。"),
    ("dian-pu", "店铺", "临街商铺建筑。"),
    ("shi-chang", "市場", "集市建筑空间。"),
    ("fang-chang", "坊墙", "里坊外围墙体。"),
    ("li-fang-men", "坊门", "里坊出入口。"),
    ("jie-shi", "街市", "城市街道建筑界面。"),
    ("xiang-dang", "巷弄", "民居之间的巷道。"),
    ("hu-tong", "胡同", "北方民居巷道。"),
    ("long-tang", "弄堂", "江南民居巷道。"),
    ("shui-xiang", "水乡", "临水民居聚落。"),
    ("shan-cun", "山村", "山地民居聚落。"),
    ("bian-sai", "边塞", "边疆军事民居。"),
    ("zhai-zi", "寨子", "堡寨式民居聚落。"),
    ("zhuang-yuan", "庄园", "大型地主庄园。"),
    ("pu-zi", "铺子", "沿街店铺。"),
    ("dang-pu", "当铺", "典当商业建筑。"),
    ("qian-zhuang", "钱庄", "金融商业建筑。"),
    ("piao-hao", "票号", "晋商金融建筑。"),
    ("yin-lou", "银楼", "金银首饰店铺。"),
    ("cha-lou", "茶楼", "饮茶社交建筑。"),
    ("xi-lou", "戏楼", "演戏楼台建筑。"),
    ("wu-tai", "舞台", "表演台面建筑。"),
    ("ji-tan", "祭坛", "礼制祭祀台（非庙宇）。"),
    ("ji-tai", "祭台", "露天祭祀平台。"),
    ("li-tai", "礼台", "礼仪活动平台。"),
    ("jiang-tai", "讲台", "讲学讲台空间。"),
    ("yue-tai", "乐台", "奏乐台榭。"),
    ("wu-chang", "舞场", "舞蹈表演场地。"),
    ("she-chang", "社场", "村落公共场地。"),
    ("gu-chang", "谷场", "晾晒谷物场地。"),
    ("mai-chang", "晒场", "院落晒场。"),
    ("cai-yuan", "菜园", "院落菜园空间。"),
    ("guo-yuan", "果园", "院落果园空间。"),
    ("hua-yuan", "花园", "种植花卉的庭院。"),
    ("zhu-lin", "竹林", "园林竹景。"),
    ("song-lin", "松林", "园林松景。"),
    ("mei-hua", "梅花", "园林梅景。"),
    ("he-hua", "荷花", "园林水景荷花。"),
    ("liu-shu", "柳树", "园林水岸植景。"),
    ("tai-ping", "太湖石", "园林叠山石料。"),
    ("huanglashi", "黄石", "园林叠山石料。"),
    ("xuan-shi", "宣石", "园林赏石。"),
    ("qi-shi", "奇石", "园林赏石。"),
    ("shui-mo", "水磨", "石作打磨工艺。"),
    ("da-mo", "打磨", "木作表面处理。"),
    ("diao-ke", "雕刻", "木石雕刻工艺。"),
    ("xian-jie", "镶嵌", "镶嵌装饰工艺。"),
    ("tie-jin", "贴金", "表面贴金箔。"),
    ("cai-hui", "彩绘", "建筑彩绘工艺。"),
    ("zhu-shi", "朱漆", "红色漆饰。"),
    ("hei-qi", "黑漆", "黑色漆饰。"),
    ("jin-qi", "金漆", "金色漆饰。"),
    ("you-qi", "油漆", "木作油漆防护。"),
    ("fang-fu", "防腐", "木作防腐处理。"),
    ("fang-huo", "防火", "建筑防火措施。"),
    ("fang-chao", "防潮", "木构防潮处理。"),
    ("fang-chong", "防虫", "木构防虫处理。"),
    ("tong-feng", "通风", "民居通风设计。"),
    ("cai-guang", "采光", "建筑采光设计。"),
    ("ge-yin", "隔音", "室内隔音设计。"),
    ("bao-wen", "保温", "民居保温设计。"),
    ("jie-neng", "节能", "传统被动式设计。"),
    ("sheng-tai", "生态", "与自然共生的营造。"),
    ("feng-shui", "风水", "传统环境选择观念。"),
    ("zuo-xiang", "坐向", "建筑朝向选择。"),
    ("kai-jian", "开间", "面阔方向的柱间。"),
    ("jin-shen", "进深", "纵深方向的间数。"),
    ("mian-kuo", "面阔", "建筑横向宽度。"),
    ("gao-du", "高度", "建筑竖向尺度。"),
    ("bi-li", "比例", "建筑各部分比例。"),
    ("mo-shu", "模数", "建筑尺度模数。"),
    ("cai-fen", "材分", "宋代材分模数。"),
    ("dou-kou", "斗口", "清代斗口模数。"),
    ("zhang-chi", "丈尺", "传统长度单位。"),
    ("bu", "步", "传统长度单位。"),
    ("chi", "尺", "传统长度单位。"),
    ("cun", "寸", "传统长度单位。"),
]

def bulk_achievements():
    out = []
    for sid, name, year, summary, tags in BULK_ACHIEVEMENTS_EXTRA:
        out.append({
            "id": sid, "name": name, "type": "achievement", "dynasty": "历代",
            "year": year, "weight": 0.4, "summary": summary, "tags": tags,
            "related": [],
        })
    for sid, name, summary in EXTRA_CRAFT_PAIRS:
        out.append({
            "id": f"craft-{sid}", "name": name, "type": "achievement", "dynasty": "历代",
            "year": 800, "weight": 0.35, "summary": summary, "tags": ["营造", "构件"],
            "related": [],
        })
    return out

def normalize_scientist(d):
    d = dict(d)
    d["type"] = "scientist"
    return d

def normalize_book(d):
    d = dict(d)
    d["type"] = "book"
    return d

def normalize_building(d):
    d = dict(d)
    d["type"] = "building"
    if "building" not in d:
        d["building"] = d["name"]
    return d

def all_bulk_stars():
    stars = []
    stars.extend(normalize_scientist(s) for s in BULK_SCIENTISTS)
    stars.extend(normalize_book(b) for b in BULK_BOOKS)
    stars.extend(normalize_building(b) for b in BULK_BUILDINGS)
    stars.extend(bulk_achievements())
    return stars
